Change HStack and VStack to Flex
TokamakUI/Tokamak pull request #466
Opened 2022-02-05 21:53 UTC by SwiftCoderJoe

Flex fixes a lot of issues with Spacer (#441) and alignment. 

I tested alignment with the demo and made a change to the spacer demo to show centering using spacers.

This is my first contribution to Tokamak so I'd appreciate review and feedback!

2022-02-06 13:41 UTC, MaxDesiatov requested changes
Overall this is great, and I don't want to discourage you from continued work on this. Efforts to clean up the layout code are greatly appreciated!

There are two test failures though, you can go to [the build summary page](https://github.com/TokamakUI/Tokamak/actions/runs/1800641428) and download "Failed snapshots" archive at the bottom.

I don't think `testGradients-A.1.png` has any meaningful changes, so it's probably fine to delete the old version and commit the new one. Maybe @carson-katri and @ezraberch as original implementors of gradients can see a substantial difference and point to what's causing it.

Here's the original:
![testGradients-A 1](https://user-images.githubusercontent.com/112310/152683721-d0b11fae-dc71-41a3-96a8-779dcd827644.png)
and the new version:
![testGradients-A 1](https://user-images.githubusercontent.com/112310/152683732-cd89b1d2-a7a3-4191-b5fa-db5124b77c89.png)

`testMaterial.1.png` change is obvious though, compare the original
![testMaterial 1](https://user-images.githubusercontent.com/112310/152683612-0d2a6098-43b6-4d7e-ac13-28bb45a48b9d.png)
to the new version
![testMaterial 1](https://user-images.githubusercontent.com/112310/152683617-9ff49861-3034-4a27-b27e-edc2ca4166dd.png)

I'm not 100% sure what's causing it, but it would be great to keep this test passing.

Also, it's highly desirable to add more snapshot tests to cover the new behavior and to prevent from breaking in the future. I guess new tests could be based on some existing demo code, but ideally shouldn't contain any text, since font rendering can change in unexpected ways on different platforms.

2022-02-06 17:18 UTC, ezraberch commented
I'm not seeing a failure in the Gradients test, either on the CI or locally. From the CI report:
```
Test Case '-[TokamakStaticHTMLTests.VisualRenderingTests testGradients]' started.
[921](https://github.com/TokamakUI/Tokamak/runs/5080472683?check_suite_focus=true#step:3:921)
[0205/235103.645806:INFO:headless_shell.cc(653)] Written to file screenshot.png.
[922](https://github.com/TokamakUI/Tokamak/runs/5080472683?check_suite_focus=true#step:3:922)
[0205/235104.949274:INFO:headless_shell.cc(653)] Written to file screenshot.png.
[923](https://github.com/TokamakUI/Tokamak/runs/5080472683?check_suite_focus=true#step:3:923)
Test Case '-[TokamakStaticHTMLTests.VisualRenderingTests testGradients]' passed (1.826 seconds).
```

If you're just going by the presence of the image in the failed screenshots upload, that's a side effect of that test passing if the image matches either of two references images (see #444).

2022-02-06 18:45 UTC, MaxDesiatov commented
Oh, that's great, thanks for checking! Then it's just one visual snapshot, and probably also a couple of HTML snapshots. And the latter can just have new versions committed.

2022-02-06 21:26 UTC, SwiftCoderJoe commented
Sorry about that! All the tests passed on my local machine, which is a Linux environment. As far as I can tell, these tests are MacOS only. It might take me a while to set up my MacOS environment, so please be patient while I fix this.

2022-02-06 21:28 UTC, MaxDesiatov commented
No problem at all! These tests are not inherently specific to macOS. Visual tests have Edge browser as a dependency, so in theory they should be runnable on Linux. HTML snapshots don't need any browser at all, so running those on Linux should be even easier.

2022-02-06 21:51 UTC, SwiftCoderJoe commented
Hmm, maybe I'm confused about how to run them then. Are they not just through `carton test`?

2022-02-06 21:55 UTC, MaxDesiatov commented
These tests don't run in the browser, because snapshot tests aren't supported in the browser due to the lack of filesystem access. That's why we can only test use snapshots for `TokamakStaticHTML` target, which is buildable on host platforms. I wonder if simple `swift test` in the root directory of the repo works for you on Linux?

2022-03-06 00:44 UTC, SwiftCoderJoe commented
Currently incredibly busy with school stuff. I'll try picking this back up when work dies down.

2022-03-06 00:44 UTC, closed without merging